#!/usr/bin/env bash
#
# Capfire server installer.
#
# What this script does (in order):
#   1. Sanity checks: root privileges, OS, required commands (git, ruby, bundle, openssl, psql).
#   2. Creates the `capfire` system user if it does not exist.
#   3. Rsyncs (or clones) the Capfire source into /opt/capfire.
#   4. Writes bin-wrappers under /opt/capfire/bin-wrappers pointing at the
#      exact ruby/bundle binaries detected on this host. That makes systemd
#      independent of PATH, RVM, rbenv or asdf shell hooks.
#   5. Runs `bundle install --deployment --without development test` as the
#      capfire user.
#   6. Generates /etc/capfire/env with a random CAPFIRE_JWT_SECRET and the
#      DATABASE_URL you provide.
#   7. Creates the apps root (default /srv/apps), owned by `capfire`.
#   8. Runs `bundle exec rails db:prepare` to create & migrate the database.
#   9. Installs /etc/systemd/system/capfire.service, enables and starts it.
#  10. Symlinks /opt/capfire/bin/capfire into /usr/local/bin/capfire so the
#      admin CLI is available on PATH.
#
# What this script does NOT do:
#   - Install Ruby. You must have Ruby 3.2+ available (via RVM, rbenv, asdf
#     or system packages). Run `ruby -v` as the invoking user first.
#   - Install Postgres. You must provide a DATABASE_URL pointing at a reachable
#     Postgres server. The DB itself is created by `db:prepare`.
#
# Usage:
#   sudo ./scripts/install-server.sh [options]
#
# Options:
#   --dir DIR            Install prefix (default: /opt/capfire)
#   --user USER          System user Capfire runs as (default: capfire)
#   --apps-root DIR      Where deployed apps live (default: /srv/apps)
#   --database-url URL   DATABASE_URL for Rails (prompts if omitted)
#   --jwt-secret SECRET  Override the autogenerated JWT secret
#   --skip-service       Do not install or start the systemd unit
#   --skip-bundle        Do not run `bundle install`
#   --skip-db            Do not run `rails db:prepare`
#   --reinstall          Tolerate an existing /opt/capfire (overwrites config+service)
#   -h, --help           Show this help
#
# Exit codes:
#   0  success
#   1  generic failure
#   2  missing dependency / prerequisite

set -euo pipefail

# ---------------------------------------------------------------------------
# Styling
# ---------------------------------------------------------------------------
if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
  C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_CYAN=$'\033[36m'
else
  C_RESET=""; C_BOLD=""; C_DIM=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_CYAN=""
fi

info()  { printf '%s›%s %s\n' "$C_CYAN"  "$C_RESET" "$*"; }
ok()    { printf '%s✓%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn()  { printf '%s!%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
fail()  { printf '%s✗%s %s\n' "$C_RED"   "$C_RESET" "$*" >&2; exit 1; }
step()  { printf '\n%s== %s ==%s\n' "$C_BOLD" "$*" "$C_RESET"; }

# ---------------------------------------------------------------------------
# Defaults & flag parsing
# ---------------------------------------------------------------------------
CAPFIRE_HOME="/opt/capfire"
CAPFIRE_USER="capfire"
APPS_ROOT="/srv/apps"
DATABASE_URL=""
JWT_SECRET=""
SKIP_SERVICE=false
SKIP_BUNDLE=false
SKIP_DB=false
REINSTALL=false

usage() {
  sed -n '3,45p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir)           CAPFIRE_HOME="$2"; shift 2 ;;
    --user)          CAPFIRE_USER="$2"; shift 2 ;;
    --apps-root)     APPS_ROOT="$2"; shift 2 ;;
    --database-url)  DATABASE_URL="$2"; shift 2 ;;
    --jwt-secret)    JWT_SECRET="$2"; shift 2 ;;
    --skip-service)  SKIP_SERVICE=true; shift ;;
    --skip-bundle)   SKIP_BUNDLE=true; shift ;;
    --skip-db)       SKIP_DB=true; shift ;;
    --reinstall)     REINSTALL=true; shift ;;
    -h|--help)       usage ;;
    *) fail "unknown argument: $1 (see --help)" ;;
  esac
done

# ---------------------------------------------------------------------------
# 1. Sanity checks
# ---------------------------------------------------------------------------
step "Preflight"

[[ $EUID -eq 0 ]] || fail "This installer must run as root (use sudo)."

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[[ -f "$SRC_DIR/Gemfile" ]] || fail "Run this script from the Capfire repo (Gemfile not found in $SRC_DIR)."

if [[ -d "$CAPFIRE_HOME" ]] && [[ "$REINSTALL" != true ]]; then
  fail "$CAPFIRE_HOME already exists. Pass --reinstall to overwrite."
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { warn "missing command: $1 — $2"; return 1; }
}

missing=0
require_cmd git      "install via apt/brew"                                          || missing=1
require_cmd ruby     "install Ruby 3.2+ via RVM/rbenv/asdf"                           || missing=1
require_cmd bundle   "gem install bundler"                                            || missing=1
require_cmd openssl  "install via apt/brew"                                           || missing=1
require_cmd rsync    "install via apt/brew"                                           || missing=1
require_cmd systemctl "systemd is required (skip with --skip-service for dev hosts)" || [[ "$SKIP_SERVICE" == true ]] || missing=1
[[ $missing -eq 0 ]] || fail "missing prerequisites — install the commands above and retry."

RUBY_BIN="$(command -v ruby)"
BUNDLE_BIN="$(command -v bundle)"
RUBY_VERSION="$("$RUBY_BIN" -e 'print RUBY_VERSION')"
info "Using ruby $RUBY_VERSION at ${C_DIM}$RUBY_BIN${C_RESET}"
info "Using bundler at ${C_DIM}$BUNDLE_BIN${C_RESET}"

case "$RUBY_VERSION" in
  3.2.*|3.3.*|3.4.*) ;;
  *) warn "Capfire is tested with Ruby 3.2.x — you have $RUBY_VERSION. Proceed at your own risk." ;;
esac

# ---------------------------------------------------------------------------
# 2. User
# ---------------------------------------------------------------------------
step "System user '$CAPFIRE_USER'"
if id "$CAPFIRE_USER" >/dev/null 2>&1; then
  ok "user already exists"
else
  useradd --system --create-home --shell /bin/bash "$CAPFIRE_USER"
  ok "created user $CAPFIRE_USER"
fi

# ---------------------------------------------------------------------------
# 3. Copy source
# ---------------------------------------------------------------------------
step "Install source into $CAPFIRE_HOME"
mkdir -p "$CAPFIRE_HOME"
# rsync excludes dev-only clutter
rsync -a --delete \
  --exclude='.git' \
  --exclude='log/' \
  --exclude='tmp/' \
  --exclude='node_modules/' \
  --exclude='client/' \
  --exclude='.ruby-lsp/' \
  --exclude='.env' --exclude='.env.*' \
  "$SRC_DIR/" "$CAPFIRE_HOME/"
mkdir -p "$CAPFIRE_HOME/log" "$CAPFIRE_HOME/tmp/pids"
chown -R "$CAPFIRE_USER:$CAPFIRE_USER" "$CAPFIRE_HOME"
ok "source synced"

# ---------------------------------------------------------------------------
# 4. bin-wrappers (systemd-friendly paths to ruby/bundle)
# ---------------------------------------------------------------------------
step "bin-wrappers"
WRAP_DIR="$CAPFIRE_HOME/bin-wrappers"
mkdir -p "$WRAP_DIR"
cat >"$WRAP_DIR/ruby" <<EOF
#!/usr/bin/env bash
exec "$RUBY_BIN" "\$@"
EOF
cat >"$WRAP_DIR/bundle" <<EOF
#!/usr/bin/env bash
exec "$BUNDLE_BIN" "\$@"
EOF
chmod +x "$WRAP_DIR/ruby" "$WRAP_DIR/bundle"
chown -R "$CAPFIRE_USER:$CAPFIRE_USER" "$WRAP_DIR"
ok "wrappers point at $(dirname "$RUBY_BIN")"

# ---------------------------------------------------------------------------
# 5. Bundle install
# ---------------------------------------------------------------------------
if [[ "$SKIP_BUNDLE" == true ]]; then
  warn "skipping bundle install (--skip-bundle)"
else
  step "bundle install"
  sudo -u "$CAPFIRE_USER" -H bash -lc \
    "cd '$CAPFIRE_HOME' && '$BUNDLE_BIN' config set --local deployment 'true' && '$BUNDLE_BIN' config set --local without 'development test' && '$BUNDLE_BIN' install --jobs=4 --retry=3"
  ok "gems installed"
fi

# ---------------------------------------------------------------------------
# 6. /etc/capfire/env
# ---------------------------------------------------------------------------
step "Environment file"
mkdir -p /etc/capfire
chmod 0750 /etc/capfire

if [[ -z "$JWT_SECRET" ]]; then
  JWT_SECRET="$(openssl rand -hex 64)"
  info "generated CAPFIRE_JWT_SECRET ($(echo -n "$JWT_SECRET" | wc -c) chars)"
fi

if [[ -z "$DATABASE_URL" ]]; then
  printf '%sDATABASE_URL%s (e.g. postgres://capfire:pass@localhost:5432/capfire_production): ' "$C_BOLD" "$C_RESET"
  read -r DATABASE_URL
  [[ -n "$DATABASE_URL" ]] || fail "DATABASE_URL is required"
fi

ENV_FILE=/etc/capfire/env
if [[ -f "$ENV_FILE" ]] && [[ "$REINSTALL" == true ]]; then
  cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
  warn "backed up existing $ENV_FILE"
fi

sed \
  -e "s|__JWT_SECRET__|$JWT_SECRET|g" \
  -e "s|__DATABASE_URL__|$DATABASE_URL|g" \
  -e "s|__APPS_ROOT__|$APPS_ROOT|g" \
  "$CAPFIRE_HOME/scripts/templates/env.example" >"$ENV_FILE"

chown root:"$CAPFIRE_USER" "$ENV_FILE"
chmod 0640 "$ENV_FILE"
ok "wrote $ENV_FILE (mode 0640, group=$CAPFIRE_USER)"

# ---------------------------------------------------------------------------
# 7. Apps root
# ---------------------------------------------------------------------------
step "Apps root $APPS_ROOT"
mkdir -p "$APPS_ROOT"
chown "$CAPFIRE_USER:$CAPFIRE_USER" "$APPS_ROOT"
chmod 0755 "$APPS_ROOT"
ok "ready"

# ---------------------------------------------------------------------------
# 8. DB prepare
# ---------------------------------------------------------------------------
if [[ "$SKIP_DB" == true ]]; then
  warn "skipping db:prepare (--skip-db)"
else
  step "rails db:prepare"
  sudo -u "$CAPFIRE_USER" -H bash -lc \
    "cd '$CAPFIRE_HOME' && set -a && . '$ENV_FILE' && set +a && RAILS_ENV=production '$BUNDLE_BIN' exec rails db:prepare"
  ok "database ready"
fi

# ---------------------------------------------------------------------------
# 9. systemd unit
# ---------------------------------------------------------------------------
if [[ "$SKIP_SERVICE" == true ]]; then
  warn "skipping systemd unit (--skip-service)"
else
  step "systemd unit"
  UNIT=/etc/systemd/system/capfire.service
  sed \
    -e "s|__CAPFIRE_USER__|$CAPFIRE_USER|g" \
    -e "s|__CAPFIRE_HOME__|$CAPFIRE_HOME|g" \
    -e "s|__CAPFIRE_APPS_ROOT__|$APPS_ROOT|g" \
    "$CAPFIRE_HOME/scripts/templates/capfire.service" >"$UNIT"
  chmod 0644 "$UNIT"
  systemctl daemon-reload
  systemctl enable capfire.service >/dev/null 2>&1
  systemctl restart capfire.service
  sleep 1
  if systemctl is-active --quiet capfire.service; then
    ok "capfire.service is active"
  else
    warn "capfire.service is not active — inspect with: journalctl -u capfire -n 200"
  fi
fi

# ---------------------------------------------------------------------------
# 10. Admin CLI symlink
# ---------------------------------------------------------------------------
step "Admin CLI"
ADMIN_SYMLINK=/usr/local/bin/capfire
ln -sf "$CAPFIRE_HOME/bin/capfire" "$ADMIN_SYMLINK"
ok "symlinked $ADMIN_SYMLINK -> $CAPFIRE_HOME/bin/capfire"

# ---------------------------------------------------------------------------
# Next steps
# ---------------------------------------------------------------------------
cat <<EOF

${C_BOLD}Capfire server installed.${C_RESET}

Next steps:
  1. Create an admin token for yourself:
       ${C_CYAN}sudo -u $CAPFIRE_USER capfire tokens create \\
         --name=admin --apps='*' --envs='production,staging' \\
         --cmds='deploy,restart,rollback,status,drain,restore'${C_RESET}

  2. Add your first app:
       ${C_CYAN}sudo -u $CAPFIRE_USER capfire project add git@github.com:yourorg/yourapp.git${C_RESET}

  3. Tail logs:
       ${C_CYAN}capfire service logs${C_RESET}   (or:  journalctl -u capfire -f)

Config lives at:   ${C_DIM}$ENV_FILE${C_RESET}
Source lives at:   ${C_DIM}$CAPFIRE_HOME${C_RESET}
Apps live under:   ${C_DIM}$APPS_ROOT${C_RESET}
EOF
